# This is a basic workflow to help you get started with Actions

name: Leaves

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: 设置JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: Clone full leaves repository
        run: |
          git config --global user.email "git@github.com"
          git config --global user.name "Actions-Runner"
          git clone "https://github.com/LeavesMC/Leaves" repository
          
      - name: Build now
        run: |
          cd repository
          chmod +x gradlew
          ./gradlew applyPatches

      - name: Compress files
        uses: edgarrc/action-7z@v1
        with:
          args: 7z a -t7z -mx=9 repository.7z ./repository/leaves-api/ ./repository/leaves-server/

      - name: Upload the zipped file
        uses: actions/upload-artifact@v3
        with:
          name: Source (Unzip 2 times)
          path: repository.7z
